# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    npm install
  displayName: 'npm install'
- script: |
    output=$(node scripts/retrieveDownloadLink.js win)
    curl "$output" --output $(Agent.TempDirectory)/edge.zip
  displayName: Downloading Edge Zip (Windows x64)
- script: |
    unzip $(Agent.TempDirectory)/edge.zip Microsoft\ Edge\ DevTools_81.0.416.72/src/out/Release/gen/devtools/* -d $(Agent.TempDirectory)/edge
    unzip $(Agent.TempDirectory)/edge.zip Microsoft\ Edge\ DevTools_81.0.416.72/src/third_party/devtools-frontend/src/front_end/* -d $(Agent.TempDirectory)/edge
  displayName: Extracting Relevant Files
- script: |
    export EDGE_CHROMIUM_PATH=$(Agent.TempDirectory)/edge/src
    export EDGE_CHROMIUM_OUT_DIR=Release
    npm run build
  displayName: 'npm build'
- script: |
    export EDGE_CHROMIUM_PATH=$(Agent.TempDirectory)/edge/src
    export EDGE_CHROMIUM_OUT_DIR=Release
    npm run test
  displayName: 'test'
- script: |
    export EDGE_CHROMIUM_PATH=$(Agent.TempDirectory)/edge/src
    export EDGE_CHROMIUM_OUT_DIR=Release
    npm run package
  displayName: 'npm run package'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'