# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    npm install
  displayName: 'npm install'
- script: |
    cd src/scripts
    output=$(node retrieveDownloadLink.js)
    echo "$output"
    echo "hello"
    curl "$output" --output edge.zip
    del url.txt
- script: |
    npm run build
  displayName: 'npm build'
- script: |
    npm run test
  displayName: 'test'
- script: |
    npm run package
  displayName: 'npm run package'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'