# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: testStage
  jobs:
  - deployment: VMDeploy
    displayName: web
    environment:
      name: 'devtools-environment'
      resourceType: VirtualMachine
      tags: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          - task: CmdLine@2
            inputs:
              script: 'set EDGE_CHROMIUM_PATH=C:\azagent\A1\edge\src && set EDGE_CHROMIUM_OUT_DIR=Release && set EDGE'
            displayName: 'Setting env Variables'
          - script: |
              npm install
            displayName: 'npm install'
          - script: |
              set EDGE_CHROMIUM_PATH=C:/azagent/A1/edge/src&&set EDGE_CHROMIUM_OUT_DIR=Release&&set EDGE
              npm run build
            displayName: 'npm build'
          - script: |
              npm run test
            displayName: 'test'