# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    npm install
  displayName: 'npm install'
- script: |
    echo Testing
    mkdir testfolder
    cd testfolder
    echo "create test folder"
    pwd
    echo "try cd"
    %CD%
    echo "try setting EDGE"
    set EDGE=%CD%
    set EDGE
    echo "try again"
    set EDGE=pwd
    set EDGE
- script: |
    output=$(node src/scripts/retrieveDownloadLink.js)
    curl "$output" --output edge.zip
  displayName: Downloading Edge Zip
- script: |
    mkdir edge
    unzip "edge.zip" src/out/Release/gen/devtools/* -d edge
  displayName: Extracting Relevant Files
- script: |
    set EDGE_CHROMIUM_PATH=%CD%/edge/src&&set EDGE_CHROMIUM_OUT_DIR=Release&&set EDGE
    npm run build
  displayName: 'npm build'
- script: |
    set EDGE_CHROMIUM_PATH=%CD%/edge&&set EDGE_CHROMIUM_OUT_DIR=Release&&set EDGE
    npm run test
  displayName: 'test'
- script: |
    set EDGE_CHROMIUM_PATH=%CD%/edge&&set EDGE_CHROMIUM_OUT_DIR=Release&&set EDGE
    npm run package
  displayName: 'npm run package'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'